version: '3.8'

services:
  monitoring-system:
    build: .
    ports:
      - "8000:8000"
    container_name: monitoring-system
    networks:
      - rede-monitoring-system
    env_file:
      - .env

networks:
  rede-monitoring-system:
    driver: bridge