name: CI Pipeline Staging

on:
    push: 
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout código
              uses: actions/checkout@v4
              
            - name: Buildar imagem Docker
              run: docker build -t monitoring-system:staging .

            - name: Rodar Container
              run: docker run -d -p 8001:8000 --name monitoring-system-staging monitoring-system:staging

            - name: Esperar serviço iniciar
              run: sleep 5

            - name: Testar healthcheck
              run: curl --fail http://localhost:8001/healthcheck

            - name: Realizar testes com pytest dentro do container
              run: docker exec monitoring-system-staging bash -c "export PYTHONPATH=/app && pytest /app/tests"